[package]
name = "blip_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
rand = "0.9.1"
ndarray = "0.16.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
semver = "1.0.26"
log = "0.4.27"
